version: '3.8'
services:
  nsi-dds:
    image: nsi-dds:latest
    container_name: nsi-dds
    build:
      context: github.com/bandwidthondemand/nsi-dds
      dockerfile: Dockerfile
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    ports:
      - 8401:8401
    volumes:
      - ./compose/config:/nsi-dds/config
      - /tmp:/nsi-dds/var/log
