sense:
  root: http://localhost:8080/
  proxy:
  driver: net.es.sense.rm.driver.nsi.NsiDriver

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

server.contextPath: /

springdoc.api-docs.enabled: true
springdoc.swagger-ui.enabled: true
springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.path: /v3/swagger-ui
