cxf.path: /nsi

nsi:
  # For NSI interactions we must have a designated NSA id.
  nsaId: urn:ogf:network:example.net:2013:nsa:application

  #########################################
  # DDS related configuration.            #
  #########################################

  # The DDS notification endpoint we will expose for callbacks.
  ddsUrl: http://localhost:8080/api/dds/v1

  # How often (in seconds) we query our remote subscription to see if it is still valid.
  ddsAuditTimer: 600

  # How long (in seconds) we wait to delete a document after it has expired.
  ddsExpiryInterval: 600

  # How many actors to instantiate in the DDS pool.
  ddsPoolSize: 4

  # The DDS server endpoint we will connect to.
  peers:
    - http://localhost:8401/dds

  #########################################
  # NSI Connection Service configuration. #
  #########################################

  # The associated NSA we will connect to for connection services.
  providerNsaId: "urn:ogf:network:opennsa.net:2015:nsa:safnari"
  providerConnectionURL: "http://localhost:9000/nsi-v2/ConnectionServiceProvider"

  # Our requester connection service endpoint.
  requesterConnectionURL: "http://localhost:8080/nsi/nsi-v2/ConnectionServiceRequester"

  # How often we audit our associated NSA for new connections.
  connectionAuditTimer: 50

  #########################################
  # NML/MRML generation configuration.    #
  #########################################

  # The topology exposed through the SENSE-N-RM.
  networkId: "urn:ogf:network:network4:2015:topology"

  # The default serviceDefinition if one is not specified.
  defaultServiceType: http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE

  # The default service type (undefined, guaranteedCapped, guaranteed, bestEffort).
  defaultType: "guaranteedCapped"

  # The default bandwidth unit.
  defaultUnits: "bps"

  # The default bandwidth granularity.
  defaultGranularity: 1

  # Control the polling of change within the network.
  modelAuditTimer: 120

  # How small should we prune the model database.
  modelPruneSize: 10

  # This was for the DDS HTTP server configuation for incoming requests but now springboot handles this.  Will need
  # a specific springboot configuration section.
  server:
    address: example.net
    port: 8401
    packageName: net.es.sense.rm.driver.nsi
    secure:
      production: false
      keyStore:
        type: JKS
        file: config/keystore.jks
        password: changeit
      trustStore:
        type: JKS
        file: config/keystore.jks
        password: changeit

  # This configures the local HTTP client (currently within DDS code).
  client:
    production: false
    keyStore:
      type: JKS
      file: config/keystore.jks
      password: changeit
    trustStore:
      type: JKS
      file: config/keystore.jks
      password: changeit

  # Left over from DDS server access control enforcement.
  accessControl:
    enabled: true
    rules:
      - access: READ
        dn:
          - "EMAILADDRESS=bob@example.com, CN=Bobby Boogie, OU=Sciences Network, O=Example Networks, L=New York, ST=NY, C=US"
        nsaId:
          - "urn:ogf:network:example.com:2013:nsa:aggr"
      - access: WRITE
        dn:
          - "CN=nsi-aggr-west.es.net, OU=Domain Control Validated"
        nsaId:
          - "urn:ogf:network:es.net:2013:nsa:nsi-aggr-west"

# Configuration for database.
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/sense-n-rm
    driver-class-name: org.postgresql.Driver
    username: sense-n-rm
    password: bubbles
    continue-on-error: true

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate

logging.level.org.springframework.web: INFO
logging.level.org.hibernate: ERROR

